export const AVAILABLE_VOICES = [
  // OpenAI voices
  {
    id: 'alloy',
    name: 'Alloy',
    language: 'pl',
    gender: 'female',
    provider: 'openai',
  },
  {
    id: 'echo',
    name: 'Echo',
    language: 'pl',
    gender: 'male',
    provider: 'openai',
  },
  {
    id: 'fable',
    name: 'Fable',
    language: 'pl',
    gender: 'female',
    provider: 'openai',
  },
  {
    id: 'onyx',
    name: 'Onyx',
    language: 'pl',
    gender: 'male',
    provider: 'openai',
  },
  {
    id: 'nova',
    name: 'Nova',
    language: 'pl',
    gender: 'female',
    provider: 'openai',
  },
  {
    id: 'shimmer',
    name: 'Shimmer',
    language: 'pl',
    gender: 'female',
    provider: 'openai',
  },

  // Google Cloud TTS voices - Chirp3-HD (najwyższa jakość)
  {
    id: 'pl-PL-Chirp3-HD-Achernar',
    name: 'Chirp3 HD Achernar',
    language: 'pl-PL',
    gender: 'female',
    provider: 'google',
  },
  {
    id: 'pl-PL-Chirp3-HD-Achird',
    name: 'Chirp3 HD Achird',
    language: 'pl-PL',
    gender: 'male',
    provider: 'google',
  },
  {
    id: 'pl-PL-Chirp3-HD-Algenib',
    name: 'Chirp3 HD Algenib',
    language: 'pl-PL',
    gender: 'female',
    provider: 'google',
  },
  {
    id: 'pl-PL-Chirp3-HD-Algieba',
    name: 'Chirp3 HD Algieba',
    language: 'pl-PL',
    gender: 'male',
    provider: 'google',
  },
  {
    id: 'pl-PL-Chirp3-HD-Alnilam',
    name: 'Chirp3 HD Alnilam',
    language: 'pl-PL',
    gender: 'female',
    provider: 'google',
  },
  {
    id: 'pl-PL-Chirp3-HD-Aoede',
    name: 'Chirp3 HD Aoede',
    language: 'pl-PL',
    gender: 'male',
    provider: 'google',
  },
  {
    id: 'pl-PL-Chirp3-HD-Autonoe',
    name: 'Chirp3 HD Autonoe',
    language: 'pl-PL',
    gender: 'female',
    provider: 'google',
  },
  {
    id: 'pl-PL-Chirp3-HD-Callirrhoe',
    name: 'Chirp3 HD Callirrhoe',
    language: 'pl-PL',
    gender: 'male',
    provider: 'google',
  },
  {
    id: 'pl-PL-Chirp3-HD-Charon',
    name: 'Chirp3 HD Charon',
    language: 'pl-PL',
    gender: 'female',
    provider: 'google',
  },
  {
    id: 'pl-PL-Chirp3-HD-Despina',
    name: 'Chirp3 HD Despina',
    language: 'pl-PL',
    gender: 'male',
    provider: 'google',
  },
  {
    id: 'pl-PL-Chirp3-HD-Enceladus',
    name: 'Chirp3 HD Enceladus',
    language: 'pl-PL',
    gender: 'female',
    provider: 'google',
  },
  {
    id: 'pl-PL-Chirp3-HD-Erinome',
    name: 'Chirp3 HD Erinome',
    language: 'pl-PL',
    gender: 'male',
    provider: 'google',
  },
  {
    id: 'pl-PL-Chirp3-HD-Fenrir',
    name: 'Chirp3 HD Fenrir',
    language: 'pl-PL',
    gender: 'female',
    provider: 'google',
  },
  {
    id: 'pl-PL-Chirp3-HD-Gacrux',
    name: 'Chirp3 HD Gacrux',
    language: 'pl-PL',
    gender: 'male',
    provider: 'google',
  },
  {
    id: 'pl-PL-Chirp3-HD-Iapetus',
    name: 'Chirp3 HD Iapetus',
    language: 'pl-PL',
    gender: 'female',
    provider: 'google',
  },
  {
    id: 'pl-PL-Chirp3-HD-Kore',
    name: 'Chirp3 HD Kore',
    language: 'pl-PL',
    gender: 'male',
    provider: 'google',
  },
  {
    id: 'pl-PL-Chirp3-HD-Laomedeia',
    name: 'Chirp3 HD Laomedeia',
    language: 'pl-PL',
    gender: 'female',
    provider: 'google',
  },
  {
    id: 'pl-PL-Chirp3-HD-Leda',
    name: 'Chirp3 HD Leda',
    language: 'pl-PL',
    gender: 'male',
    provider: 'google',
  },
  {
    id: 'pl-PL-Chirp3-HD-Orus',
    name: 'Chirp3 HD Orus',
    language: 'pl-PL',
    gender: 'female',
    provider: 'google',
  },
  {
    id: 'pl-PL-Chirp3-HD-Puck',
    name: 'Chirp3 HD Puck',
    language: 'pl-PL',
    gender: 'male',
    provider: 'google',
  },
  {
    id: 'pl-PL-Chirp3-HD-Pulcherrima',
    name: 'Chirp3 HD Pulcherrima',
    language: 'pl-PL',
    gender: 'female',
    provider: 'google',
  },
  {
    id: 'pl-PL-Chirp3-HD-Rasalgethi',
    name: 'Chirp3 HD Rasalgethi',
    language: 'pl-PL',
    gender: 'male',
    provider: 'google',
  },
  {
    id: 'pl-PL-Chirp3-HD-Sadachbia',
    name: 'Chirp3 HD Sadachbia',
    language: 'pl-PL',
    gender: 'female',
    provider: 'google',
  },
  {
    id: 'pl-PL-Chirp3-HD-Sadaltager',
    name: 'Chirp3 HD Sadaltager',
    language: 'pl-PL',
    gender: 'male',
    provider: 'google',
  },
  {
    id: 'pl-PL-Chirp3-HD-Schedar',
    name: 'Chirp3 HD Schedar',
    language: 'pl-PL',
    gender: 'female',
    provider: 'google',
  },
  {
    id: 'pl-PL-Chirp3-HD-Sulafat',
    name: 'Chirp3 HD Sulafat',
    language: 'pl-PL',
    gender: 'male',
    provider: 'google',
  },
  {
    id: 'pl-PL-Chirp3-HD-Umbriel',
    name: 'Chirp3 HD Umbriel',
    language: 'pl-PL',
    gender: 'female',
    provider: 'google',
  },
  {
    id: 'pl-PL-Chirp3-HD-Vindemiatrix',
    name: 'Chirp3 HD Vindemiatrix',
    language: 'pl-PL',
    gender: 'male',
    provider: 'google',
  },
  {
    id: 'pl-PL-Chirp3-HD-Zephyr',
    name: 'Chirp3 HD Zephyr',
    language: 'pl-PL',
    gender: 'female',
    provider: 'google',
  },
  {
    id: 'pl-PL-Chirp3-HD-Zubenelgenubi',
    name: 'Chirp3 HD Zubenelgenubi',
    language: 'pl-PL',
    gender: 'male',
    provider: 'google',
  },

  // Google Cloud TTS voices - Wavenet (wysoka jakość)
  {
    id: 'pl-PL-Wavenet-A',
    name: 'Wavenet A (Female)',
    language: 'pl-PL',
    gender: 'female',
    provider: 'google',
  },
  {
    id: 'pl-PL-Wavenet-B',
    name: 'Wavenet B (Female)',
    language: 'pl-PL',
    gender: 'female',
    provider: 'google',
  },
  {
    id: 'pl-PL-Wavenet-C',
    name: 'Wavenet C (Male)',
    language: 'pl-PL',
    gender: 'male',
    provider: 'google',
  },
  {
    id: 'pl-PL-Wavenet-D',
    name: 'Wavenet D (Male)',
    language: 'pl-PL',
    gender: 'male',
    provider: 'google',
  },
  {
    id: 'pl-PL-Wavenet-F',
    name: 'Wavenet F',
    language: 'pl-PL',
    gender: 'female',
    provider: 'google',
  },
  {
    id: 'pl-PL-Wavenet-G',
    name: 'Wavenet G (Male)',
    language: 'pl-PL',
    gender: 'male',
    provider: 'google',
  },

  // Google Cloud TTS voices - Standard (podstawowa jakość)
  {
    id: 'pl-PL-Standard-A',
    name: 'Standard A (Female)',
    language: 'pl-PL',
    gender: 'female',
    provider: 'google',
  },
  {
    id: 'pl-PL-Standard-B',
    name: 'Standard B (Female)',
    language: 'pl-PL',
    gender: 'female',
    provider: 'google',
  },
  {
    id: 'pl-PL-Standard-C',
    name: 'Standard C (Male)',
    language: 'pl-PL',
    gender: 'male',
    provider: 'google',
  },
  {
    id: 'pl-PL-Standard-D',
    name: 'Standard D (Male)',
    language: 'pl-PL',
    gender: 'male',
    provider: 'google',
  },
  {
    id: 'pl-PL-Standard-F',
    name: 'Standard F',
    language: 'pl-PL',
    gender: 'female',
    provider: 'google',
  },
  {
    id: 'pl-PL-Standard-G',
    name: 'Standard G',
    language: 'pl-PL',
    gender: 'male',
    provider: 'google',
  },
];

export const TRANSLATOR_PROVIDERS = [
  {
    id: 'openai',
    name: 'OpenAI',
    description: 'Tłumaczenie za pomocą modeli OpenAI',
  },
  {
    id: 'google',
    name: 'Google Translate',
    description: 'Tłumaczenie przez Google Cloud Translate',
  },
  {
    id: 'deepseek',
    name: 'DeepSeek',
    description: 'Tłumaczenie przez DeepSeek API',
  },
];

export const TTS_PROVIDERS = [
  {
    id: 'openai',
    name: 'OpenAI TTS',
    description: 'Wysokiej jakości głosy od OpenAI',
  },
  {
    id: 'google',
    name: 'Google Cloud TTS',
    description: 'Głosy Google Cloud z obsługą SSML',
  },
  { id: 'none', name: 'Wyłączone', description: 'Bez generowania audio' },
];
